name: Build and Publish Spliit Image

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Image name (e.g. ghcr.io/OWNER/REPO/spliit)'
        required: true
        default: 'ghcr.io/null-icicle/hypnotic-mist/spliit'
      build_repository:
        description: 'Repository for the aplication (e.g. spliit-app/spliit)'
        required: true
        default: 'spliit-app/spliit'
  schedule:
    - cron: '15 23 * * *' # every 24h

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ inputs.image_name || 'ghcr.io/null-icicle/hypnotic-mist/spliit' }}
      BUILD_REPOSITORY: ${{ inputs.build_repository || 'spliit-app/spliit' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Spliit version
        id: latest_version
        run: |
          version=$(curl -s https://api.github.com/repos/${{ env.BUILD_REPOSITORY }}/releases/latest | jq -r .tag_name | sed 's/v//')
          major=$(echo "$version" | cut -d. -f1)
          minor=$(echo "$version" | cut -d. -f2)
          bugfix=$(echo "$version" | cut -d. -f3)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "major=$major" >> $GITHUB_OUTPUT
          echo "minor=$minor" >> $GITHUB_OUTPUT
          echo "bugfix=$bugfix" >> $GITHUB_OUTPUT

      - name: Checkout the Application Repository at Specific Tag
        uses: actions/checkout@v4
        with:
          repository: ${{ env.BUILD_REPOSITORY }}
          ref: ${{ steps.latest_version.outputs.version }}
          path: build_repository

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./build_repository
          file: ./build_repository/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.latest_version.outputs.version }}
            ${{ env.IMAGE_NAME }}:${{ steps.latest_version.outputs.major }}
            ${{ env.IMAGE_NAME }}:${{ steps.latest_version.outputs.major }}.${{ steps.latest_version.outputs.minor }}
            ${{ env.IMAGE_NAME }}:${{ steps.latest_version.outputs.major }}.${{ steps.latest_version.outputs.minor }}.${{ steps.latest_version.outputs.bugfix }}
          build-args: |
            LATEST_VERSION=${{ steps.latest_version.outputs.version }}
